name: Build
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Compile
      id: compile
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: '21'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    - run: ./gradlew build --stacktrace --no-daemon
      
    - name: Upload Build to Releases
      if: (steps.compile.outcome == 'success')
      run: gh release upload $(grep "mod_version" "gradle.properties"|cut -d'=' -f2) $(grep "archives_base_name" "gradle.properties"|cut -d'=' -f2)-$(grep "mod_version" "gradle.properties"|cut -d'=' -f2).jar
