name: Build
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ascii-image-converter
        version: 1.0

    - name: Fun Thing
      run: ascii-image-converter ${{ github.workspace }}/src/main/resources/assets/vulkanite/icon.png -C
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: '21'
          
    - name: Caching
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ${{ github.workspace }}/build/loom-cache
          ${{ github.workspace }}/build/processIncludeJars
          
    - name: Compile
      id: compile
      run: ./gradlew build --stacktrace --warning-mode all
      
    - name: Upload Build to Releases
      env:
        GH_TOKEN: ${{ github.token }}
      if: (steps.compile.outcome == 'success')
      run: |
        cd ${{ github.workspace }}/build/libs
        gh release upload $(grep "mod_version" "../../gradle.properties"|cut -d'=' -f2) $(grep "archives_base_name" "../../gradle.properties"|cut -d'=' -f2)-$(grep "mod_version" "../../gradle.properties"|cut -d'=' -f2).jar
